# -*- coding: utf-8 -*-
"""block_2_embeddings_multigpu_py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152Usgms-z_ohJ15jZ5EukvtbTHJI9ltl
"""

#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
==========================================================================================
🚀 BLOCK 2 — MULTI-GPU EMBEDDINGS (F1 / RESUMABLE / SAFE)

PURPOSE
- Generate sentence-transformer embeddings for the filtered Brazilian tweet corpus.
- Multi-GPU: one worker process per GPU.
- Resumable: per-input-file outputs + DONE markers.
- Does NOT rewrite the tweet CSVs (preserves all original columns by design).
- Outputs:
    (1) embeddings shards: .npz (ids + embeddings float16)
    (2) metadata shards:  .csv.gz (message_id + source_file + row_in_file + n_chars)

INPUT ASSUMPTION
- Input directory contains .csv.gz files with at least: message_id, text
- This is intended AFTER the final discursive/semantic filtering step
  (target scale: a few million rows, not hundreds of millions).

==========================================================================================
"""

import os
import sys
import gc
import json
import time
import math
import gzip
import shutil
import signal
from pathlib import Path
from datetime import datetime
from multiprocessing import get_context

import numpy as np
import pandas as pd
import torch
from sentence_transformers import SentenceTransformer

# =============================================================================
# CONFIG
# =============================================================================

PROJECT_ROOT = Path("/n/netscratch/cga/Lab/rpalbuquerque/paper_TGIS")

# ✅ After your final filter, files should be here:
INPUT_ROOT = PROJECT_ROOT / "tweets_brazil" / "semantic_filtered"

# Output dir for embeddings
OUT_ROOT = PROJECT_ROOT / "block_2_embeddings"
OUT_EMB  = OUT_ROOT / "embeddings_npz"
OUT_META = OUT_ROOT / "metadata_csv"
DONE_DIR = OUT_ROOT / "_done"
LOG_DIR  = OUT_ROOT / "_logs"

OUT_EMB.mkdir(parents=True, exist_ok=True)
OUT_META.mkdir(parents=True, exist_ok=True)
DONE_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)

# Model
EMBED_MODEL_NAME = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
MAX_SEQ_LEN = 256

# Performance knobs
DEFAULT_BATCH_SIZE = 2048         # will auto-shrink on OOM
MAX_ROWS_PER_CHUNK = 200_000      # streaming inside a file (keeps RAM stable)
WRITE_EVERY_ROWS   = 200_000      # write embeddings per chunk

# Numeric format
EMB_DTYPE = np.float16            # smaller + fast

# GPU config
NUM_GPUS = int(os.environ.get("NUM_GPUS", "4"))  # you have 4
GPU_IDS  = list(range(NUM_GPUS))

# CPU threading (tokenization + pandas)
CPU_THREADS = int(os.environ.get("CPU_THREADS", str(max(8, (os.cpu_count() or 32) // 2))))
os.environ["OMP_NUM_THREADS"] = str(CPU_THREADS)
os.environ["MKL_NUM_THREADS"] = str(CPU_THREADS)
torch.set_num_threads(CPU_THREADS)

# =============================================================================
# LOGGING
# =============================================================================

def log(msg: str):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)

def safe_write_text(path: Path, text: str):
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text)
    tmp.replace(path)

def done_marker_for(infile: Path) -> Path:
    # unique stable id: filename only is fine because folder is flat in semantic_filtered
    return DONE_DIR / f"{infile.name}.done.json"

def outputs_for(infile: Path, chunk_id: int):
    # One input file may be written in multiple chunks
    base = infile.name.replace(".csv.gz", "")
    emb_path  = OUT_EMB  / f"{base}.chunk{chunk_id:05d}.npz"
    meta_path = OUT_META / f"{base}.chunk{chunk_id:05d}.csv.gz"
    return emb_path, meta_path

# =============================================================================
# GPU WORKER
# =============================================================================

def encode_texts(embedder: SentenceTransformer, texts, batch_size: int):
    """
    Robust GPU encoder with automatic batch shrinking on OOM.
    """
    bs = batch_size
    while True:
        try:
            with torch.inference_mode():
                emb = embedder.encode(
                    texts,
                    batch_size=bs,
                    show_progress_bar=False,
                    convert_to_numpy=True,
                    normalize_embeddings=True
                )
            return emb, bs
        except RuntimeError as e:
            if "out of memory" in str(e).lower():
                torch.cuda.empty_cache()
                bs = max(64, bs // 2)
                if bs == 64:
                    raise
                continue
            raise

def worker_main(gpu_id: int, file_list: list):
    """
    One process bound to one GPU.
    """
    os.environ["CUDA_VISIBLE_DEVICES"] = str(gpu_id)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    log(f"🧠 [GPU {gpu_id}] Loading model on device={device} | threads={CPU_THREADS}")
    embedder = SentenceTransformer(EMBED_MODEL_NAME, device=device)
    embedder.max_seq_length = MAX_SEQ_LEN
    log(f"✅ [GPU {gpu_id}] Model loaded: {EMBED_MODEL_NAME}")

    kept_files = 0
    kept_rows  = 0

    for idx, infile in enumerate(file_list):
        dm = done_marker_for(infile)
        if dm.exists():
            continue

        t0 = time.time()
        chunk_id = 0
        rows_total_infile = 0

        try:
            # Stream within file to keep memory stable
            reader = pd.read_csv(
                infile,
                compression="gzip",
                dtype=str,
                chunksize=MAX_ROWS_PER_CHUNK,
                low_memory=False
            )

            for df in reader:
                if df.empty:
                    continue
                if "message_id" not in df.columns or "text" not in df.columns:
                    continue

                df["text"] = df["text"].astype(str)
                # Drop NA texts only (rows), preserve columns in original dataset by not rewriting it
                df = df[df["text"].notna()]
                if df.empty:
                    continue

                texts = df["text"].tolist()
                ids   = df["message_id"].astype(str).tolist()

                # Encode (GPU)
                emb, used_bs = encode_texts(embedder, texts, DEFAULT_BATCH_SIZE)

                # Convert dtype
                emb = emb.astype(EMB_DTYPE, copy=False)

                # Output paths
                emb_path, meta_path = outputs_for(infile, chunk_id)

                # Write embeddings shard
                # Store ids as numpy array of strings (object); ok for npz
                np.savez_compressed(
                    emb_path,
                    message_id=np.array(ids, dtype=object),
                    embeddings=emb
                )

                # Write metadata shard (csv.gz) for joins / audits
                meta = pd.DataFrame({
                    "message_id": ids,
                    "__source_file": infile.name,
                    "__row_in_chunk": np.arange(len(ids), dtype=np.int32),
                    "__text_nchars": [len(t) for t in texts],
                    "__emb_dim": emb.shape[1],
                    "__emb_dtype": str(EMB_DTYPE),
                    "__batch_used": used_bs
                })
                meta.to_csv(meta_path, index=False, compression="gzip")

                nrows = len(ids)
                rows_total_infile += nrows
                kept_rows += nrows

                # Housekeeping
                del df, texts, ids, emb, meta
                gc.collect()
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()

                chunk_id += 1

            # Mark DONE (per input file)
            safe_write_text(dm, json.dumps({
                "infile": str(infile),
                "gpu_id": gpu_id,
                "chunks_written": chunk_id,
                "rows_embedded": rows_total_infile,
                "finished_utc": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
            }))

            kept_files += 1
            dt = time.time() - t0
            log(f"✅ [GPU {gpu_id}] DONE {infile.name} | rows={rows_total_infile:,} | chunks={chunk_id:,} | {dt:,.1f}s")

        except Exception as e:
            # fail-soft: log and continue
            err_path = LOG_DIR / f"FAILED_gpu{gpu_id}.log"
            with open(err_path, "a") as f:
                f.write(f"{datetime.utcnow().isoformat()} | {infile} | {repr(e)}\n")
            log(f"⚠️ [GPU {gpu_id}] FAILED {infile.name}: {repr(e)}")
            continue

    log(f"🏁 [GPU {gpu_id}] Worker finished | files={kept_files:,} | rows={kept_rows:,}")
    return kept_files, kept_rows

# =============================================================================
# SHARDING FILES ACROSS GPUS
# =============================================================================

def shard_files(files, n_shards: int):
    shards = [[] for _ in range(n_shards)]
    for i, f in enumerate(files):
        shards[i % n_shards].append(f)
    return shards

# =============================================================================
# MAIN
# =============================================================================

def main():
    print("\n>>> BLOCK 2 SCRIPT STARTED <<<", flush=True)
    print("Python executable:", sys.executable, flush=True)
    print("PID:", os.getpid(), flush=True)

    files = sorted(INPUT_ROOT.glob("*.csv.gz"))
    if not files:
        raise RuntimeError(f"❌ No input files found in {INPUT_ROOT}")

    log("=" * 110)
    log("🚀 BLOCK 2 — MULTI-GPU EMBEDDINGS (RESUMABLE)")
    log(f"Project root : {PROJECT_ROOT}")
    log(f"Input root   : {INPUT_ROOT}")
    log(f"Output root  : {OUT_ROOT}")
    log(f"Files found  : {len(files):,}")
    log(f"GPUs         : {GPU_IDS}")
    log(f"CPU threads  : {CPU_THREADS}")
    log(f"Model        : {EMBED_MODEL_NAME}")
    log(f"Batch        : {DEFAULT_BATCH_SIZE} (auto-shrink on OOM)")
    log(f"Chunk rows   : {MAX_ROWS_PER_CHUNK:,}")
    log("=" * 110)

    # Shard input files across GPUs
    shards = shard_files(files, len(GPU_IDS))

    ctx = get_context("spawn")  # CUDA-safe
    procs = []
    pipes = []

    # We use spawn processes via ctx.Process
    results_path = OUT_ROOT / "run_summary.json"

    # Start one process per GPU
    for gpu_id, shard in zip(GPU_IDS, shards):
        p = ctx.Process(target=worker_main, args=(gpu_id, shard), daemon=False)
        p.start()
        procs.append(p)
        log(f"🚀 Launched worker for GPU {gpu_id} | files={len(shard):,}")

    # Wait
    for p in procs:
        p.join()

    log("✅ BLOCK 2 FINISHED (all GPU workers joined)")
    log(f"Outputs: {OUT_ROOT}")
    log("=" * 110)

if __name__ == "__main__":
    main()