# -*- coding: utf-8 -*-
"""block_2_multi_gpu_embeddings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152Usgms-z_ohJ15jZ5EukvtbTHJI9ltl
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
BLOCK 2 — Multi-GPU Embeddings (Ultra-fast, Streaming, Resumable)

Input:
  tweets_brazil/final_corpus/year=YYYY/month=MM/sample_YYYY_MM.csv.gz

Output:
  block_2_embeddings/
    ├─ embeddings_npz/  (npz: message_id + embeddings float16)
    ├─ metadata_csv/    (csv.gz: message_id + year + month + source_file + row_index)
    └─ _done/           (json checkpoints per input file)

Rules:
  - DO NOT rewrite original CSVs
  - DO NOT alter text
  - Embeddings stored separately
  - Fully resumable
  - Multi-GPU: 1 process per GPU
"""

import os
import re
import json
import time
import argparse
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd


# -------------------------------
# Logging
# -------------------------------

def ts():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def log(msg):
    print(f"[{ts()}] {msg}", flush=True)


# -------------------------------
# Paths / IO helpers
# -------------------------------

def ensure_dir(p: Path):
    p.mkdir(parents=True, exist_ok=True)

def list_input_files(input_root: Path):
    return sorted(input_root.glob("year=*/month=*/sample_*.csv.gz"))

def parse_year_month_from_path(p: Path):
    m_year  = re.search(r"year=(\d{4})", str(p))
    m_month = re.search(r"month=(\d{1,2})", str(p))
    year  = m_year.group(1) if m_year else ""
    month = m_month.group(1) if m_month else ""
    return year, month

def done_marker_path(done_dir: Path, in_file: Path):
    safe = str(in_file).replace("/", "__")
    return done_dir / f"{safe}.done.json"

def atomic_write_npz(out_path: Path, **arrays):
    tmp = out_path.with_suffix(out_path.suffix + ".tmp")
    np.savez_compressed(tmp, **arrays)
    tmp.replace(out_path)

def atomic_write_csv_gz(df: pd.DataFrame, out_path: Path):
    tmp = out_path.with_suffix(out_path.suffix + ".tmp")
    df.to_csv(tmp, index=False, compression="gzip")
    tmp.replace(out_path)

def pandas_engine():
    # Try PyArrow for faster CSV parsing if available
    try:
        import pyarrow  # noqa: F401
        return "pyarrow"
    except Exception:
        return None


# -------------------------------
# Worker (one GPU)
# -------------------------------

def embed_one_file(
    in_file: Path,
    out_root: Path,
    text_col: str,
    id_col: str,
    batch_size: int,
    chunk_rows: int,
    max_rows: int,
    gpu_id: int,
    seed: int,
    omp_threads: int,
):
    import torch
    from sentence_transformers import SentenceTransformer

    # Avoid CPU thread oversubscription per GPU worker
    os.environ["OMP_NUM_THREADS"] = str(omp_threads)
    os.environ["MKL_NUM_THREADS"] = str(omp_threads)

    assert torch.cuda.is_available(), "CUDA not available. Block 2 requires GPUs."
    torch.cuda.set_device(gpu_id)
    device = f"cuda:{gpu_id}"

    # Extra speed knobs
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.set_float32_matmul_precision("high")

    model_name = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
    log(f"[GPU {gpu_id}] Loading model: {model_name}")
    model = SentenceTransformer(model_name, device=device)

    emb_dir  = out_root / "embeddings_npz"
    meta_dir = out_root / "metadata_csv"
    done_dir = out_root / "_done"
    ensure_dir(emb_dir); ensure_dir(meta_dir); ensure_dir(done_dir)

    done_path = done_marker_path(done_dir, in_file)
    if done_path.exists():
        log(f"[GPU {gpu_id}] SKIP (done): {in_file}")
        return

    # Validate columns (read just header)
    header = pd.read_csv(in_file, compression="gzip", nrows=1, low_memory=False)
    cols = set(header.columns)
    if id_col not in cols:
        raise RuntimeError(f"Missing id_col='{id_col}' in {in_file}")
    if text_col not in cols:
        raise RuntimeError(f"Missing text_col='{text_col}' in {in_file}")

    year, month = parse_year_month_from_path(in_file)
    file_tag = f"y{year}_m{month}__{in_file.stem}"

    engine = pandas_engine()
    if engine:
        log(f"[GPU {gpu_id}] Using pandas engine='{engine}' for faster CSV parsing")

    np.random.seed(seed)

    t0 = time.time()
    total_rows = 0
    chunk_idx = 0

    reader = pd.read_csv(
        in_file,
        compression="gzip",
        low_memory=False,
        usecols=[id_col, text_col],
        chunksize=chunk_rows,
        engine=engine if engine else None
    )

    log(f"[GPU {gpu_id}] Start: {in_file}")

    # Inference-only mode (speed + memory)
    with torch.inference_mode():
        for df in reader:
            if max_rows and total_rows >= max_rows:
                break

            if max_rows:
                remaining = max_rows - total_rows
                if remaining <= 0:
                    break
                if len(df) > remaining:
                    df = df.iloc[:remaining].copy()

            if len(df) == 0:
                continue

            ids = df[id_col].astype(str).to_numpy()
            texts = df[text_col].fillna("").astype(str).tolist()
            n = len(texts)

            # Encode with fp16 autocast for speed
            emb_list = []
            for start in range(0, n, batch_size):
                bt = texts[start:start + batch_size]
                with torch.autocast(device_type="cuda", dtype=torch.float16):
                    embs = model.encode(
                        bt,
                        batch_size=min(batch_size, len(bt)),
                        show_progress_bar=False,
                        convert_to_numpy=True,
                        normalize_embeddings=False
                    )
                embs = embs.astype(np.float16, copy=False)
                emb_list.append(embs)

            embeddings = np.vstack(emb_list)
            if embeddings.shape[0] != n:
                raise RuntimeError("Embedding rows mismatch")

            emb_out  = emb_dir  / f"{file_tag}__chunk{chunk_idx:05d}.npz"
            meta_out = meta_dir / f"{file_tag}__chunk{chunk_idx:05d}.csv.gz"

            meta_df = pd.DataFrame({
                "message_id": ids,
                "year": year,
                "month": month,
                "source_file": str(in_file),
                "row_index_in_chunk": np.arange(n, dtype=np.int32),
                "chunk_index": np.full(n, chunk_idx, dtype=np.int32),
            })

            atomic_write_npz(emb_out, message_id=ids, embeddings=embeddings)
            atomic_write_csv_gz(meta_df, meta_out)

            total_rows += n
            chunk_idx += 1

            if chunk_idx % 10 == 0:
                elapsed = time.time() - t0
                rps = total_rows / max(elapsed, 1e-9)
                log(f"[GPU {gpu_id}] Progress: {file_tag} rows={total_rows:,} chunks={chunk_idx:,} rps~{rps:,.0f}")

    elapsed = time.time() - t0
    done_payload = {
        "input_file": str(in_file),
        "year": year,
        "month": month,
        "gpu_id": gpu_id,
        "rows_embedded": int(total_rows),
        "chunks_written": int(chunk_idx),
        "batch_size": int(batch_size),
        "chunk_rows": int(chunk_rows),
        "model": model_name,
        "dtype": "float16",
        "completed_at": datetime.utcnow().isoformat(),
        "elapsed_sec": float(elapsed),
        "omp_threads": int(omp_threads),
        "engine": engine if engine else "default",
    }
    with open(done_path, "w") as f:
        json.dump(done_payload, f, indent=2)

    log(f"[GPU {gpu_id}] DONE: {in_file} rows={total_rows:,} chunks={chunk_idx:,} elapsed={elapsed/60:.1f} min")


# -------------------------------
# Launcher (spawn one worker per GPU)
# -------------------------------

def split_round_robin(items, k):
    buckets = [[] for _ in range(k)]
    for i, it in enumerate(items):
        buckets[i % k].append(it)
    return buckets

def launcher_main(args):
    input_root = Path(args.input_root)
    out_root   = Path(args.output_root)
    ensure_dir(out_root)

    files = list_input_files(input_root)
    if not files:
        raise RuntimeError(f"No input files found under: {input_root}")

    gpu_ids = [int(x) for x in args.gpus.split(",") if x.strip() != ""]
    if not gpu_ids:
        raise RuntimeError("No GPUs specified. Use --gpus 0,1,2,3")

    log(f"Files found: {len(files):,}")
    log(f"GPUs: {gpu_ids}")

    if args.limit_files:
        files = files[:args.limit_files]
        log(f"LIMIT_FILES enabled: processing only first {len(files)} file(s)")

    shards = split_round_robin(files, len(gpu_ids))

    import subprocess
    procs = []
    for local_rank, gpu_id in enumerate(gpu_ids):
        shard_file = out_root / f"_shard_gpu{gpu_id}.txt"
        with open(shard_file, "w") as f:
            for p in shards[local_rank]:
                f.write(str(p) + "\n")

        cmd = [
            "python", str(Path(__file__).name),
            "--mode", "worker",
            "--gpu-id", str(gpu_id),
            "--shard-file", str(shard_file),
            "--input-root", str(input_root),
            "--output-root", str(out_root),
            "--text-col", args.text_col,
            "--id-col", args.id_col,
            "--batch-size", str(args.batch_size),
            "--chunk-rows", str(args.chunk_rows),
            "--seed", str(args.seed),
            "--omp-threads", str(args.omp_threads),
        ]
        if args.max_rows:
            cmd += ["--max-rows", str(args.max_rows)]

        log(f"Launching GPU {gpu_id}: {' '.join(cmd)}")
        procs.append(subprocess.Popen(cmd))

    exit_codes = [p.wait() for p in procs]
    if any(code != 0 for code in exit_codes):
        raise SystemExit(f"One or more workers failed: {exit_codes}")

    log("✅ BLOCK 2 COMPLETED (all GPU workers finished successfully)")

def worker_main(args):
    shard_paths = []
    with open(args.shard_file, "r") as f:
        for line in f:
            s = line.strip()
            if s:
                shard_paths.append(Path(s))

    if not shard_paths:
        log(f"[GPU {args.gpu_id}] No files in shard. Exit.")
        return

    log(f"[GPU {args.gpu_id}] Shard files: {len(shard_paths):,}")

    out_root = Path(args.output_root)

    for in_file in shard_paths:
        embed_one_file(
            in_file=in_file,
            out_root=out_root,
            text_col=args.text_col,
            id_col=args.id_col,
            batch_size=args.batch_size,
            chunk_rows=args.chunk_rows,
            max_rows=args.max_rows,
            gpu_id=args.gpu_id,
            seed=args.seed,
            omp_threads=args.omp_threads,
        )

    log(f"[GPU {args.gpu_id}] Worker finished.")


# -------------------------------
# CLI
# -------------------------------

def build_argparser():
    ap = argparse.ArgumentParser(description="BLOCK 2 — Multi-GPU Embeddings (Ultra-fast, Resumable)")
    ap.add_argument("--mode", choices=["launcher", "worker"], default="launcher")

    ap.add_argument("--input-root",  default="tweets_brazil/final_corpus", type=str)
    ap.add_argument("--output-root", default="block_2_embeddings", type=str)

    ap.add_argument("--text-col", default="text", type=str)
    ap.add_argument("--id-col",   default="message_id", type=str)

    ap.add_argument("--gpus", default="0,1,2,3", type=str)
    ap.add_argument("--gpu-id", default=0, type=int)
    ap.add_argument("--shard-file", default="", type=str)

    ap.add_argument("--batch-size", default=256, type=int)
    ap.add_argument("--chunk-rows", default=200_000, type=int)
    ap.add_argument("--max-rows", default=0, type=int)

    ap.add_argument("--seed", default=42, type=int)
    ap.add_argument("--limit-files", default=0, type=int)

    # Key speed control: keep this low-ish per GPU worker to avoid fighting for CPUs
    ap.add_argument("--omp-threads", default=8, type=int)

    return ap

def main():
    args = build_argparser().parse_args()
    if args.mode == "launcher":
        launcher_main(args)
    else:
        if not args.shard_file:
            raise RuntimeError("--shard-file is required in worker mode")
        worker_main(args)

if __name__ == "__main__":
    main()