# -*- coding: utf-8 -*-
"""block0_base.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hquF24yHE3EQhyXgRUo4pwpvrttHgTQM
"""

#!/usr/bin/env python3
# ============================================================
# BLOCK 0 — BRAZIL FILTER (HPC SAFE / RESUME / FAIL-SOFT)
#
# - Filters GeoTweets to Brazil (bbox + date)
# - Keeps ALL original columns
# - Chunked (memory-safe)
# - Skips malformed files (logs & continues)
# - Resume via DONE markers
# - Progress bar in terminal (tqdm)
#
# USAGE EXAMPLE:
#   python block0_base.py --start-year 2010 --end-year 2012 --workers 10
#
# ============================================================

import os
import gc
import json
import argparse
import hashlib
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np
from tqdm import tqdm
import multiprocessing as mp


# ============================================================
# ARGUMENTS
# ============================================================
def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--start-year", type=int, required=True)
    ap.add_argument("--end-year", type=int, required=True)
    ap.add_argument("--workers", type=int, default=10)
    ap.add_argument("--chunksize", type=int, default=250_000)
    return ap.parse_args()


# ============================================================
# PATHS (AJUSTADOS PARA tweets_brazil)
# ============================================================
RAW_ROOT = Path("/n/holylabs/LABS/cga/Lab/data/geo-tweets/cga-sbg-tweets/")

OUT_ROOT = Path(
    "/n/netscratch/cga/Lab/rpalbuquerque/paper_TGIS/tweets_brazil/"
)

OUT_DIR  = OUT_ROOT / "filtered_batches_BR"
DONE_DIR = OUT_ROOT / "_done"
LOG_DIR  = OUT_ROOT / "_logs"

FAILED_LOG   = LOG_DIR / "failed_files.txt"
MANIFEST_LOG = LOG_DIR / "manifest.csv"

OUT_DIR.mkdir(parents=True, exist_ok=True)
DONE_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)

if not MANIFEST_LOG.exists():
    MANIFEST_LOG.write_text("timestamp_utc,file,status,parts_written\n")


# ============================================================
# FILTER PARAMETERS (BRAZIL)
# ============================================================
DATE_MIN = pd.Timestamp("2010-01-01")
DATE_MAX = pd.Timestamp("2023-07-31 23:59:59")

BR_LAT_MIN, BR_LAT_MAX = -34.0,  5.5
BR_LON_MIN, BR_LON_MAX = -74.0, -34.0


# ============================================================
# HELPERS
# ============================================================
def utcnow():
    return datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")


def file_id(fpath: Path) -> str:
    rel = fpath.relative_to(RAW_ROOT).as_posix()
    return hashlib.md5(rel.encode()).hexdigest()[:12]


def done_marker(fpath: Path) -> Path:
    return DONE_DIR / f"{file_id(fpath)}.done"


def atomic_write(df: pd.DataFrame, outpath: Path):
    tmp = outpath.with_suffix(outpath.suffix + ".tmp")
    df.to_csv(tmp, index=False, compression="gzip")
    tmp.replace(outpath)


def detect_columns(df: pd.DataFrame):
    cols = {c.lower(): c for c in df.columns}
    if not all(k in cols for k in ("latitude", "longitude", "date")):
        raise ValueError("Missing required columns (latitude/longitude/date)")
    return cols["latitude"], cols["longitude"], cols["date"]


def log_failed(fpath: Path, reason: str):
    with open(FAILED_LOG, "a") as f:
        f.write(f"{utcnow()} | {fpath} | {reason}\n")


def log_manifest(fpath: Path, status: str, parts: int):
    with open(MANIFEST_LOG, "a") as f:
        f.write(f"{utcnow()},{fpath},{status},{parts}\n")


# ============================================================
# WORKER (FAIL-SOFT, MEMORY-SAFE)
# ============================================================
def process_file(args_tuple):
    fpath_str, chunksize = args_tuple
    fpath = Path(fpath_str)

    if done_marker(fpath).exists():
        return "SKIPPED"

    parts_written = 0

    try:
        reader = pd.read_csv(
            fpath,
            sep="\t",
            compression="gzip",
            dtype=str,
            chunksize=chunksize,
            on_bad_lines="skip",
            engine="c"
        )

        latc = lonc = datec = None

        for chunk_idx, chunk in enumerate(reader):

            if latc is None:
                latc, lonc, datec = detect_columns(chunk)

            lat = pd.to_numeric(chunk[latc], errors="coerce")
            lon = pd.to_numeric(chunk[lonc], errors="coerce")
            dts = pd.to_datetime(chunk[datec], errors="coerce")

            mask = (
                lat.between(BR_LAT_MIN, BR_LAT_MAX)
                & lon.between(BR_LON_MIN, BR_LON_MAX)
                & dts.between(DATE_MIN, DATE_MAX)
            )

            if mask.any():
                out = chunk.loc[mask].copy()
                years  = dts.loc[mask].dt.year.values
                months = dts.loc[mask].dt.month.values

                for (yy, mm) in np.unique(
                    np.stack([years, months], axis=1), axis=0
                ):
                    yy, mm = int(yy), int(mm)
                    odir = OUT_DIR / f"year={yy}" / f"month={mm}"
                    odir.mkdir(parents=True, exist_ok=True)

                    outpath = odir / f"{file_id(fpath)}.chunk{chunk_idx:05d}.csv.gz"

                    if not outpath.exists():
                        sel = (years == yy) & (months == mm)
                        atomic_write(out.loc[sel], outpath)
                        parts_written += 1

            del chunk
            gc.collect()

        done_marker(fpath).write_text(
            json.dumps({
                "file": str(fpath),
                "finished_utc": utcnow(),
                "parts_written": parts_written
            })
        )

        log_manifest(fpath, "OK", parts_written)
        return "OK"

    except Exception as e:
        log_failed(fpath, repr(e))
        log_manifest(fpath, "FAILED", parts_written)
        return "FAILED"


# ============================================================
# MAIN
# ============================================================
def main():
    args = parse_args()

    files = []
    for year in range(args.start_year, args.end_year + 1):
        ydir = RAW_ROOT / str(year)
        if ydir.exists():
            files.extend(sorted(ydir.glob("*.csv.gz")))

    print("==============================================", flush=True)
    print("BLOCK 0 — Brazil Filter", flush=True)
    print(f"Years       : {args.start_year}–{args.end_year}", flush=True)
    print(f"Files found : {len(files)}", flush=True)
    print(f"Workers     : {args.workers}", flush=True)
    print(f"Chunksize   : {args.chunksize}", flush=True)
    print("==============================================", flush=True)

    ctx = mp.get_context("spawn")

    with ctx.Pool(processes=args.workers) as pool:
        iterable = ((str(f), args.chunksize) for f in files)

        for _ in tqdm(
            pool.imap_unordered(process_file, iterable),
            total=len(files),
            desc=f"Block0 [{args.start_year}-{args.end_year}]",
            dynamic_ncols=True,
            mininterval=1.0
        ):
            pass

    print("==============================================", flush=True)
    print("BLOCK 0 COMPLETED", flush=True)
    print("==============================================", flush=True)


if __name__ == "__main__":
    main()