# -*- coding: utf-8 -*-
"""block_1_2_temporal_stratified_sampling_with_cap

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152Usgms-z_ohJ15jZ5EukvtbTHJI9ltl
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
BLOCK 1.2 — Temporal Stratified Sampling with Monthly Cap (TGIS-ready)

Goal:
- Construct a temporally stratified corpus (year–month)
- Allow high-activity months to contribute more observations
- Prevent dominance via a fixed monthly cap
- No global target size
- Fully deterministic
- NO column removal
- NO text modification
- CPU only

Input:
tweets_brazil/discursive_filtered/year=YYYY/month=MM/*.csv.gz

Output:
tweets_brazil/final_corpus/year=YYYY/month=MM/sample_YYYY_MM.csv.gz

QC:
tweets_brazil/final_corpus/_qc/month_counts.csv
"""

import os
import glob
import gzip
import json
import random
from pathlib import Path
from datetime import datetime

import pandas as pd

# =========================
# CONFIG (INTERNAL ONLY)
# =========================

INPUT_ROOT  = Path("tweets_brazil/discursive_filtered")
OUTPUT_ROOT = Path("tweets_brazil/final_corpus")
QC_DIR      = OUTPUT_ROOT / "_qc"

BASE_PER_MONTH = 30_000   # implicit floor
MAX_PER_MONTH  = 60_000   # hard cap to avoid dominance

RANDOM_SEED = 42

# =========================
# INIT
# =========================

random.seed(RANDOM_SEED)
QC_DIR.mkdir(parents=True, exist_ok=True)

records = []

print("=" * 100)
print("🚀 BLOCK 1.2 — Temporal Stratified Sampling with Monthly Cap")
print(f"Input root : {INPUT_ROOT}")
print(f"Output root: {OUTPUT_ROOT}")
print(f"BASE_PER_MONTH = {BASE_PER_MONTH}")
print(f"MAX_PER_MONTH  = {MAX_PER_MONTH}")
print(f"Seed           = {RANDOM_SEED}")
print("=" * 100)

# =========================
# MAIN LOOP
# =========================

for year_dir in sorted(INPUT_ROOT.glob("year=*")):
    year = year_dir.name.split("=")[1]

    for month_dir in sorted(year_dir.glob("month=*")):
        month = month_dir.name.split("=")[1]

        files = sorted(month_dir.glob("*.csv.gz"))
        if not files:
            continue

        print(f"[{year}-{month}] Reading {len(files)} file(s)...")

        df_list = []
        for f in files:
            df = pd.read_csv(f, compression="gzip", low_memory=False)
            df_list.append(df)

        df_month = pd.concat(df_list, ignore_index=True)
        n_available = len(df_month)

        # determine sample size
        if n_available <= BASE_PER_MONTH:
            n_sample = n_available
        elif n_available <= MAX_PER_MONTH:
            n_sample = n_available
        else:
            n_sample = MAX_PER_MONTH

        # deterministic sampling
        if n_sample < n_available:
            df_sample = df_month.sample(
                n=n_sample,
                random_state=RANDOM_SEED,
                replace=False
            )
        else:
            df_sample = df_month

        # output path
        out_dir = OUTPUT_ROOT / f"year={year}" / f"month={month}"
        out_dir.mkdir(parents=True, exist_ok=True)

        out_file = out_dir / f"sample_{year}_{month}.csv.gz"

        df_sample.to_csv(
            out_file,
            index=False,
            compression="gzip"
        )

        records.append({
            "year": year,
            "month": month,
            "available": n_available,
            "sampled": len(df_sample)
        })

        print(
            f"[{year}-{month}] available={n_available:,} "
            f"sampled={len(df_sample):,}"
        )

# =========================
# QC OUTPUT
# =========================

qc_df = pd.DataFrame(records).sort_values(["year", "month"])
qc_file = QC_DIR / "month_counts.csv"
qc_df.to_csv(qc_file, index=False)

summary = {
    "block": "1.2",
    "strategy": "temporal stratified sampling with monthly cap",
    "base_per_month": BASE_PER_MONTH,
    "max_per_month": MAX_PER_MONTH,
    "seed": RANDOM_SEED,
    "total_tweets": int(qc_df["sampled"].sum()),
    "generated_at": datetime.utcnow().isoformat()
}

with open(QC_DIR / "summary.json", "w") as f:
    json.dump(summary, f, indent=2)

print("=" * 100)
print("✅ BLOCK 1.2 COMPLETED")
print(f"Total tweets in final corpus: {summary['total_tweets']:,}")
print(f"QC saved to: {QC_DIR}")
print("=" * 100)