# -*- coding: utf-8 -*-
"""block_1_semantic_filter_fixed.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152Usgms-z_ohJ15jZ5EukvtbTHJI9ltl
"""

#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
==========================================================================================
🚀 BLOCK 1 — SEMANTIC + LANGUAGE + LOCATION FILTER (FIXED)

PURPOSE
- Remove non-semantic tweets prior to topic analysis
- Preserve ALL original columns (NO SCHEMA LOSS)
- Filter by:
    • Semantic validity (regex)
    • tweet_lang == 'pt' (if column exists)
    • place indicates Brazil (if column exists)
    • user_location indicates Brazil (if column exists)
- Overwrite previous (buggy) semantic_filtered outputs

DESIGN
- Massive CPU parallelism (one file per process)
- Streaming-safe
- Crash-safe (per-file)
- NO usecols, NO column selection
==========================================================================================
"""

import os
import re
import gc
from pathlib import Path
from multiprocessing import Pool, cpu_count

import pandas as pd
from tqdm import tqdm

# =============================================================================
# PATHS
# =============================================================================

PROJECT_ROOT = Path("/n/netscratch/cga/Lab/rpalbuquerque/paper_TGIS")

INPUT_ROOT  = PROJECT_ROOT / "tweets_brazil" / "filtered_batches_BR"
OUTPUT_ROOT = PROJECT_ROOT / "tweets_brazil" / "semantic_filtered"

OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

# =============================================================================
# FILTER PARAMETERS
# =============================================================================

MIN_CHARS = 40
MIN_ALPHA_RATIO = 0.60
MIN_ALPHA_TOKEN_RATIO = 0.50

# Use all cores (Ferrari mode)
N_WORKERS = max(1, (cpu_count() or 112) - 2)

# =============================================================================
# REGEX
# =============================================================================

URL_ONLY_RE = re.compile(r"^\s*(https?:\/\/\S+)\s*$", re.IGNORECASE)
REPEAT_RE   = re.compile(r"(.)\1{5,}")  # e.g. kkkkkkk / !!!!!!!!

BRAZIL_RE = re.compile(
    r"\b(brasil|brazil|br)\b", re.IGNORECASE
)

# =============================================================================
# SEMANTIC FILTER
# =============================================================================

def is_semantic(text: str) -> bool:
    if not isinstance(text, str):
        return False

    text = text.strip()
    if len(text) < MIN_CHARS:
        return False

    if URL_ONLY_RE.match(text):
        return False

    if REPEAT_RE.search(text):
        return False

    total_chars = len(text)
    alpha_chars = sum(c.isalpha() for c in text)
    if alpha_chars / total_chars < MIN_ALPHA_RATIO:
        return False

    tokens = text.split()
    if not tokens:
        return False

    alpha_tokens = sum(any(c.isalpha() for c in tok) for tok in tokens)
    if alpha_tokens / len(tokens) < MIN_ALPHA_TOKEN_RATIO:
        return False

    return True

# =============================================================================
# AUX FILTERS (SAFE — ONLY IF COLUMN EXISTS)
# =============================================================================

def is_pt_lang(row) -> bool:
    if "tweet_lang" in row:
        return str(row["tweet_lang"]).lower() == "pt"
    return True  # do not filter if column missing


def is_brazil_place(row) -> bool:
    if "place" in row:
        return bool(BRAZIL_RE.search(str(row["place"])))
    return True


def is_brazil_user_location(row) -> bool:
    if "user_location" in row:
        return bool(BRAZIL_RE.search(str(row["user_location"])))
    return True

# =============================================================================
# FILE PROCESSOR (ONE FILE = ONE PROCESS)
# =============================================================================

def process_file(path: Path) -> int:
    out_path = OUTPUT_ROOT / path.name

    try:
        df = pd.read_csv(
            path,
            compression="gzip",
            dtype=str,
            low_memory=False
        )
    except Exception:
        return 0

    if df.empty or "text" not in df.columns:
        return 0

    df["text"] = df["text"].astype(str)

    # Semantic filter
    mask = df["text"].apply(is_semantic)

    # Language / location filters (only if columns exist)
    if "tweet_lang" in df.columns:
        mask &= df.apply(is_pt_lang, axis=1)

    if "place" in df.columns:
        mask &= df.apply(is_brazil_place, axis=1)

    if "user_location" in df.columns:
        mask &= df.apply(is_brazil_user_location, axis=1)

    df = df[mask]

    if df.empty:
        return 0

    # OVERWRITE previous buggy output
    df.to_csv(out_path, index=False, compression="gzip")

    n = len(df)
    del df
    gc.collect()

    return n

# =============================================================================
# MAIN
# =============================================================================

def main():
    files = sorted(INPUT_ROOT.glob("**/*.csv.gz"))
    if not files:
        raise RuntimeError("❌ No input files found.")

    print("=" * 100)
    print("🚀 BLOCK 1 — SEMANTIC + LANGUAGE + LOCATION FILTER (FIXED)")
    print(f"Input files : {len(files):,}")
    print(f"Workers     : {N_WORKERS}")
    print(f"Output dir  : {OUTPUT_ROOT}")
    print("⚠️  Overwriting previous semantic_filtered outputs")
    print("=" * 100)

    total_kept = 0

    with Pool(processes=N_WORKERS) as pool:
        for kept in tqdm(
            pool.imap_unordered(process_file, files),
            total=len(files),
            dynamic_ncols=True
        ):
            total_kept += kept

    print("=" * 100)
    print("✅ BLOCK 1 FIXED COMPLETED SUCCESSFULLY")
    print(f"Tweets kept for topic analysis: {total_kept:,}")
    print("=" * 100)

if __name__ == "__main__":
    main()