# -*- coding: utf-8 -*-
"""block_1_1_discursive_filter.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CIfcFHxUJ-XkTWulrnuqPRgEVif2G0_
"""

#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
==========================================================================================
🚀 BLOCK 1.1 — DISCURSIVE FILTER (F1 / MAX CPU / NO COLUMN DROPS)

PURPOSE
- Build the *discursive* corpus aligned with the paper's macrothemes:
  emotions, aspirations, reflections, struggles, religious/sports affections, etc.
- Remove non-discursive noise (URL-only, emoji-only, bot-like patterns, RT/replies, spam).
- Preserve ALL original columns from Block 0 (no column drops, ever).
- Crash-safe / resumable.

INPUT
- Block 0 output: /tweets_brazil/filtered_batches_BR/year=YYYY/month=M/*.csv.gz
  (CSV.gz files, full original schema).

OUTPUT
- /tweets_brazil/discursive_filtered/year=YYYY/month=M/*.csv.gz
  (same structure, same columns, fewer rows).

PERFORMANCE
- Massive CPU parallelism: one input file per worker process.
- Streaming read with chunksize to keep memory stable.
- Vectorized pandas string operations (no slow Python per-row loops).

USAGE
  cd /n/netscratch/cga/Lab/rpalbuquerque/paper_TGIS
  python block_1_1_discursive_filter_py.py
==========================================================================================
"""

import os
import re
import gc
import sys
import json
from pathlib import Path
from datetime import datetime
from multiprocessing import Pool, cpu_count, get_context

import pandas as pd
from tqdm import tqdm

# =============================================================================
# CONFIG
# =============================================================================

PROJECT_ROOT = Path("/n/netscratch/cga/Lab/rpalbuquerque/paper_TGIS")

INPUT_ROOT  = PROJECT_ROOT / "tweets_brazil" / "filtered_batches_BR"
OUTPUT_ROOT = PROJECT_ROOT / "tweets_brazil" / "discursive_filtered"

DONE_DIR = OUTPUT_ROOT / "_done"
LOG_DIR  = OUTPUT_ROOT / "_logs"

OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
DONE_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)

# Use essentially all cores (leave a bit for OS / filesystem)
N_WORKERS = int(os.environ.get("WORKERS", str(max(1, (cpu_count() or 112) - 2))))
CHUNKSIZE = int(os.environ.get("CHUNKSIZE", "200000"))

# ---- Discursive thresholds (tunable; chosen to target ~few million scale)
MIN_CHARS          = int(os.environ.get("MIN_CHARS", "50"))    # stronger than 40
MIN_WORDS          = int(os.environ.get("MIN_WORDS", "8"))
MIN_ALPHA_CHARS    = int(os.environ.get("MIN_ALPHA_CHARS", "20"))
MIN_ALPHA_RATIO    = float(os.environ.get("MIN_ALPHA_RATIO", "0.55"))
MAX_HASHTAGS       = int(os.environ.get("MAX_HASHTAGS", "6"))
MAX_MENTIONS       = int(os.environ.get("MAX_MENTIONS", "6"))
MAX_DIGIT_RATIO    = float(os.environ.get("MAX_DIGIT_RATIO", "0.35"))

# Optional language/location filters (only applied if the columns exist)
ENFORCE_PT_LANG     = os.environ.get("ENFORCE_PT_LANG", "1") == "1"
ENFORCE_BR_LOCATION = os.environ.get("ENFORCE_BR_LOCATION", "1") == "1"

# =============================================================================
# REGEX (compiled once)
# =============================================================================

# URL-only text (just a link, maybe with surrounding whitespace)
URL_ONLY_RE = re.compile(r"^\s*(https?:\/\/\S+)\s*$", re.IGNORECASE)

# Common RT and reply patterns (non-discursive for our macrotheme analysis)
RT_PREFIX_RE    = re.compile(r"^\s*rt\s+@\w+:", re.IGNORECASE)
REPLY_PREFIX_RE = re.compile(r"^\s*@\w+", re.IGNORECASE)

# Excessive character repetition (kkkkkkkk, aaaaaaa, !!!!!!!!!!)
REPEAT_RE = re.compile(r"(.)\1{6,}")

# A loose "letter" regex for Portuguese (Latin ranges incl. accents)
LETTER_RE = re.compile(r"[A-Za-zÀ-ÖØ-öø-ÿ]")

# If a string has at least one letter => not emoji/punct-only
HAS_LETTER_RE = re.compile(r".*[A-Za-zÀ-ÖØ-öø-ÿ].*")

# Emoji-only / punct-only proxy: no letters at all
NO_LETTER_RE = re.compile(r"^[^A-Za-zÀ-ÖØ-öø-ÿ]+$")

# =============================================================================
# LOGGING
# =============================================================================

def log(msg: str):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)

def done_marker_for(infile: Path) -> Path:
    # Preserve uniqueness with relative path hashed into filename
    rel = infile.relative_to(INPUT_ROOT).as_posix().replace("/", "__")
    return DONE_DIR / f"{rel}.done.json"

def out_path_for(infile: Path) -> Path:
    rel = infile.relative_to(INPUT_ROOT)
    out = OUTPUT_ROOT / rel
    out.parent.mkdir(parents=True, exist_ok=True)
    return out

def atomic_write_csv_gz(df: pd.DataFrame, outpath: Path):
    tmp = outpath.with_suffix(outpath.suffix + ".tmp")
    df.to_csv(tmp, index=False, compression="gzip")
    tmp.replace(outpath)

def safe_json_write(path: Path, obj: dict):
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(obj, ensure_ascii=False))
    tmp.replace(path)

# =============================================================================
# CORE FILTER (vectorized)
# =============================================================================

def discursive_mask(df: pd.DataFrame) -> pd.Series:
    """
    Returns a boolean mask selecting discursive, stance-bearing, semantically rich tweets.
    Preserves all columns: this function filters rows only.
    """
    if "text" not in df.columns:
        return pd.Series([False] * len(df), index=df.index)

    text = df["text"].astype("string").fillna("").str.strip()

    # 1) Basic length / words
    m_len   = text.str.len().fillna(0) >= MIN_CHARS
    n_words = text.str.split().str.len().fillna(0)
    m_words = n_words >= MIN_WORDS

    # 2) Remove URL-only
    m_not_url_only = ~text.str.match(URL_ONLY_RE, na=False)

    # 3) Remove RTs / replies (very high noise for macrotheme discourse)
    m_not_rt    = ~text.str.match(RT_PREFIX_RE, na=False)
    m_not_reply = ~text.str.match(REPLY_PREFIX_RE, na=False)

    # 4) Must contain letters (drop emoji-only / punctuation-only)
    m_has_letter = text.str.match(HAS_LETTER_RE, na=False)

    # 5) Drop excessive repetitions
    m_no_repeat = ~text.str.contains(REPEAT_RE, na=False)

    # 6) Letter density constraints (proxy for semantic content)
    #    alpha_count via regex findall count (vectorized count)
    alpha_count = text.str.count(LETTER_RE)
    total_len   = text.str.len().clip(lower=1)
    alpha_ratio = (alpha_count / total_len)

    m_alpha_min   = alpha_count >= MIN_ALPHA_CHARS
    m_alpha_ratio = alpha_ratio >= MIN_ALPHA_RATIO

    # 7) Drop digit-heavy strings (often IDs, spam, scoreboard, etc.)
    digit_count = text.str.count(r"\d")
    digit_ratio = (digit_count / total_len)
    m_digit_ok  = digit_ratio <= MAX_DIGIT_RATIO

    # 8) Spammy hashtag/mention bursts
    hashtag_count  = text.str.count(r"#")
    mention_count  = text.str.count(r"@")
    m_hash_ok      = hashtag_count <= MAX_HASHTAGS
    m_mention_ok   = mention_count <= MAX_MENTIONS

    # Optional: enforce Portuguese language if column exists
    m_lang = pd.Series([True] * len(df), index=df.index)
    if ENFORCE_PT_LANG:
        lang_col = None
        for c in ["tweet_lang", "user_lang", "lang", "text_lang"]:
            if c in df.columns:
                lang_col = c
                break
        if lang_col is not None:
            lang = df[lang_col].astype("string").fillna("").str.lower().str.strip()
            # Accept common PT variants
            m_lang = lang.isin(["pt", "pt_br", "pt-br", "por", "portuguese", "português", "ptbr"]) | lang.str.startswith("pt")

    # Optional: enforce Brazil location (only if column exists)
    m_loc = pd.Series([True] * len(df), index=df.index)
    if ENFORCE_BR_LOCATION:
        loc_col = None
        for c in ["place", "user_location", "location"]:
            if c in df.columns:
                loc_col = c
                break
        if loc_col is not None:
            loc = df[loc_col].astype("string").fillna("").str.lower()
            # permissive contains to avoid false negatives
            m_loc = loc.str.contains("brasil|brazil", regex=True, na=False)

    return (
        m_len
        & m_words
        & m_not_url_only
        & m_not_rt
        & m_not_reply
        & m_has_letter
        & m_no_repeat
        & m_alpha_min
        & m_alpha_ratio
        & m_digit_ok
        & m_hash_ok
        & m_mention_ok
        & m_lang
        & m_loc
    )

# =============================================================================
# WORKER: process one input file (streaming)
# =============================================================================

def process_one_file(infile_str: str) -> dict:
    infile = Path(infile_str)
    dm = done_marker_for(infile)
    outpath = out_path_for(infile)

    if dm.exists() and outpath.exists():
        return {"file": infile_str, "status": "SKIPPED", "kept": 0, "read": 0}

    kept_total = 0
    read_total = 0

    try:
        reader = pd.read_csv(
            infile,
            compression="gzip",
            dtype=str,              # preserve schema; no dtype inference surprises
            chunksize=CHUNKSIZE,
            low_memory=False
        )

        out_written = False

        for chunk_idx, df in enumerate(reader):
            if df is None or df.empty:
                continue

            read_total += len(df)

            mask = discursive_mask(df)
            if mask.any():
                out_df = df.loc[mask].copy()   # keep ALL columns
                kept = len(out_df)
                kept_total += kept

                # Append per chunk into one output file
                # (write header only once)
                if not out_written:
                    atomic_write_csv_gz(out_df, outpath)
                    out_written = True
                else:
                    # append safely: write temp then concatenate by appending text
                    # gzip append is supported; pandas doesn't do append to gzip cleanly,
                    # so we do a controlled append via text mode.
                    # Strategy: write chunk to tmp gz and then append decompressed lines (excluding header) to main gz.
                    tmp = outpath.with_suffix(outpath.suffix + f".chunk{chunk_idx:05d}.tmp.gz")
                    out_df.to_csv(tmp, index=False, compression="gzip")

                    # Append lines excluding header
                    import gzip as _gzip
                    with _gzip.open(outpath, "ab") as dst, _gzip.open(tmp, "rb") as src:
                        # skip header line in src
                        _ = src.readline()
                        shutil.copyfileobj(src, dst)
                    tmp.unlink(missing_ok=True)

                del out_df
                gc.collect()

            del df
            gc.collect()

        safe_json_write(dm, {
            "file": infile_str,
            "finished_utc": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            "read_rows": read_total,
            "kept_rows": kept_total,
            "output": str(outpath)
        })

        return {"file": infile_str, "status": "OK", "kept": kept_total, "read": read_total}

    except Exception as e:
        err_path = LOG_DIR / "failed_files.log"
        with open(err_path, "a") as f:
            f.write(f"{datetime.utcnow().isoformat()} | {infile_str} | {repr(e)}\n")
        return {"file": infile_str, "status": "FAILED", "kept": kept_total, "read": read_total}

# =============================================================================
# MAIN
# =============================================================================

def main():
    log("=" * 110)
    log("🚀 BLOCK 1.1 — DISCURSIVE FILTER (F1 / MAX CPU / NO COLUMN DROPS)")
    log(f"Project root : {PROJECT_ROOT}")
    log(f"Input root   : {INPUT_ROOT}")
    log(f"Output root  : {OUTPUT_ROOT}")
    log(f"Workers      : {N_WORKERS}")
    log(f"Chunksize    : {CHUNKSIZE:,}")
    log(f"MIN_CHARS    : {MIN_CHARS}")
    log(f"MIN_WORDS    : {MIN_WORDS}")
    log(f"MIN_ALPHA    : {MIN_ALPHA_CHARS} | ratio >= {MIN_ALPHA_RATIO}")
    log(f"MAX_HASHTAGS : {MAX_HASHTAGS}")
    log(f"MAX_MENTIONS : {MAX_MENTIONS}")
    log(f"PT filter    : {ENFORCE_PT_LANG}")
    log(f"BR loc filter: {ENFORCE_BR_LOCATION}")
    log("=" * 110)

    files = sorted(INPUT_ROOT.glob("**/*.csv.gz"))
    if not files:
        raise RuntimeError(f"❌ No input .csv.gz found under {INPUT_ROOT}")

    log(f"📦 Input files discovered: {len(files):,}")

    ctx = get_context("spawn")
    total_read = 0
    total_kept = 0
    n_ok = n_fail = n_skip = 0

    with ctx.Pool(processes=N_WORKERS) as pool:
        for r in tqdm(pool.imap_unordered(process_one_file, map(str, files)), total=len(files), dynamic_ncols=True):
            if r["status"] == "OK":
                n_ok += 1
            elif r["status"] == "FAILED":
                n_fail += 1
            else:
                n_skip += 1
            total_read += r["read"]
            total_kept += r["kept"]

    log("=" * 110)
    log("✅ BLOCK 1.1 COMPLETED")
    log(f"Files OK     : {n_ok:,}")
    log(f"Files SKIPPED: {n_skip:,}")
    log(f"Files FAILED : {n_fail:,}")
    log(f"Rows read    : {total_read:,}")
    log(f"Rows kept    : {total_kept:,}")
    log(f"Output root  : {OUTPUT_ROOT}")
    log("=" * 110)

if __name__ == "__main__":
    main()