# -*- coding: utf-8 -*-
"""block_1_2_temporal_sampling_py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152Usgms-z_ohJ15jZ5EukvtbTHJI9ltl
"""

#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
==========================================================================================
🚀 BLOCK 1.2 — TEMPORAL STRATIFIED SAMPLING (FINAL / PATH-BASED)

PURPOSE
- Reduce discursive_filtered corpus (~192M rows) to ~5–7M tweets
- Preserve temporal balance using year/month FROM PATH
- Produce final corpus for embeddings & LLM (paper-faithful)

DESIGN
- CPU-bound, fully parallel
- Deterministic sampling
- Does NOT remove or alter columns
- Uses year=YYYY/month=MM folder structure (robust)
==========================================================================================
"""

import os
import gc
import random
import re
from pathlib import Path
from multiprocessing import Pool, cpu_count
from collections import defaultdict

import pandas as pd
from tqdm import tqdm

# =============================================================================
# CONFIG
# =============================================================================

PROJECT_ROOT = Path("/n/netscratch/cga/Lab/rpalbuquerque/paper_TGIS")

INPUT_ROOT  = PROJECT_ROOT / "tweets_brazil" / "discursive_filtered"
OUTPUT_ROOT = PROJECT_ROOT / "tweets_brazil" / "final_corpus"

OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

TARGET_PER_MONTH = 50_000
RANDOM_SEED = 42

N_WORKERS = max(1, (cpu_count() or 112) - 2)

YEAR_RE  = re.compile(r"year=(\d{4})")
MONTH_RE = re.compile(r"month=(\d{1,2})")

# =============================================================================
# HELPERS
# =============================================================================

def extract_year_month_from_path(path: Path):
    y = YEAR_RE.search(str(path))
    m = MONTH_RE.search(str(path))
    if not y or not m:
        return None
    return int(y.group(1)), int(m.group(1))


def process_file(path: Path):
    ym = extract_year_month_from_path(path)
    if ym is None:
        return None, None

    try:
        df = pd.read_csv(path, compression="gzip", dtype=str, low_memory=False)
    except Exception:
        return ym, None

    if df.empty:
        return ym, None

    return ym, df


# =============================================================================
# MAIN
# =============================================================================

def main():
    random.seed(RANDOM_SEED)

    files = sorted(INPUT_ROOT.glob("**/*.csv.gz"))
    assert files, f"❌ No files found under {INPUT_ROOT}"

    print("=" * 110)
    print("🚀 BLOCK 1.2 — TEMPORAL STRATIFIED SAMPLING (PATH-BASED)")
    print(f"Input files  : {len(files):,}")
    print(f"Workers      : {N_WORKERS}")
    print(f"Target/month : {TARGET_PER_MONTH:,}")
    print("=" * 110)

    buckets = defaultdict(list)

    with Pool(processes=N_WORKERS) as pool:
        for (ym, df) in tqdm(
            pool.imap_unordered(process_file, files),
            total=len(files),
            dynamic_ncols=True
        ):
            if ym is None or df is None or df.empty:
                continue
            buckets[ym].append(df)

    total_kept = 0

    for (y, m) in sorted(buckets.keys()):
        df_month = pd.concat(buckets[(y, m)], ignore_index=True)
        n_total = len(df_month)

        if n_total > TARGET_PER_MONTH:
            df_month = df_month.sample(
                n=TARGET_PER_MONTH,
                random_state=RANDOM_SEED
            )

        out_dir = OUTPUT_ROOT / f"year={y}" / f"month={m:02d}"
        out_dir.mkdir(parents=True, exist_ok=True)

        out_path = out_dir / f"sample_{y}_{m:02d}.csv.gz"
        df_month.to_csv(out_path, index=False, compression="gzip")

        kept = len(df_month)
        total_kept += kept

        print(f"✅ {y}-{m:02d} | kept {kept:,} / {n_total:,}")

        del df_month
        gc.collect()

    print("=" * 110)
    print("✅ BLOCK 1.2 COMPLETED SUCCESSFULLY")
    print(f"📦 FINAL CORPUS SIZE: {total_kept:,} tweets")
    print(f"📂 Output root      : {OUTPUT_ROOT}")
    print("=" * 110)


if __name__ == "__main__":
    main()