# -*- coding: utf-8 -*-
"""block_1_2_temporal_stratified_sampling_normalized

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152Usgms-z_ohJ15jZ5EukvtbTHJI9ltl
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
BLOCK 1.2 (CORRECTED) — Temporal Stratified Sampling with Month Normalization
TGIS-ready, SAFE VERSION

Key fixes:
- Normalize month folders (1, 01 → 01)
- Merge duplicated months BEFORE sampling
- New isolated output directory (no overwrite risk)

Rules respected:
- NO column removal
- NO text modification
- Deterministic (fixed seed)
- CPU only
"""

import json
import random
from pathlib import Path
from datetime import datetime
import pandas as pd

# =============================================================================
# PROJECT ROOT (ABSOLUTE, SAFE)
# =============================================================================

PROJECT_ROOT = Path(__file__).resolve().parent

INPUT_ROOT = PROJECT_ROOT / "tweets_brazil" / "discursive_filtered"

# 🚨 NEW OUTPUT (ISOLATED)
OUTPUT_ROOT = PROJECT_ROOT / "tweets_brazil" / "final_corpus_v2_normalized"
QC_DIR = OUTPUT_ROOT / "_qc"

# =============================================================================
# SAMPLING CONFIG
# =============================================================================

BASE_PER_MONTH = 30_000
MAX_PER_MONTH  = 60_000
RANDOM_SEED    = 42

random.seed(RANDOM_SEED)

# =============================================================================
# INIT
# =============================================================================

QC_DIR.mkdir(parents=True, exist_ok=True)
records = []

print("=" * 100)
print("🚀 BLOCK 1.2 (CORRECTED) — Temporal Stratified Sampling (Month Normalized)")
print(f"Project root : {PROJECT_ROOT}")
print(f"Input root   : {INPUT_ROOT}")
print(f"Output root  : {OUTPUT_ROOT}")
print(f"BASE_PER_MONTH = {BASE_PER_MONTH}")
print(f"MAX_PER_MONTH  = {MAX_PER_MONTH}")
print(f"Seed           = {RANDOM_SEED}")
print("=" * 100)

# =============================================================================
# MAIN LOOP
# =============================================================================

for year_dir in sorted(INPUT_ROOT.glob("year=*")):
    year = year_dir.name.split("=")[1]

    # Collect all month folders → normalized month
    month_groups = {}

    for month_dir in year_dir.glob("month=*"):
        raw_month = month_dir.name.split("=")[1]
        norm_month = f"{int(raw_month):02d}"  # 🔑 normalization

        month_groups.setdefault(norm_month, []).append(month_dir)

    for month, dirs in sorted(month_groups.items()):
        print(f"[{year}-{month}] Merging {len(dirs)} source month folder(s)")

        df_list = []
        files_read = 0

        for d in dirs:
            files = sorted(d.glob("*.csv.gz"))
            for f in files:
                df = pd.read_csv(f, compression="gzip", low_memory=False)
                df_list.append(df)
                files_read += 1

        if not df_list:
            continue

        df_month = pd.concat(df_list, ignore_index=True)
        n_available = len(df_month)

        # Determine sample size
        if n_available <= BASE_PER_MONTH:
            n_sample = n_available
        elif n_available <= MAX_PER_MONTH:
            n_sample = n_available
        else:
            n_sample = MAX_PER_MONTH

        # Deterministic sampling
        if n_sample < n_available:
            df_sample = df_month.sample(
                n=n_sample,
                random_state=RANDOM_SEED,
                replace=False
            )
        else:
            df_sample = df_month

        # Output path
        out_dir = OUTPUT_ROOT / f"year={year}" / f"month={month}"
        out_dir.mkdir(parents=True, exist_ok=True)

        out_file = out_dir / f"sample_{year}_{month}.csv.gz"

        df_sample.to_csv(
            out_file,
            index=False,
            compression="gzip"
        )

        records.append({
            "year": year,
            "month": month,
            "source_month_folders": len(dirs),
            "files_read": files_read,
            "available": n_available,
            "sampled": len(df_sample)
        })

        print(
            f"[{year}-{month}] available={n_available:,} "
            f"sampled={len(df_sample):,} "
            f"(from {len(dirs)} folder(s))"
        )

# =============================================================================
# QC OUTPUT
# =============================================================================

qc_df = pd.DataFrame(records).sort_values(["year", "month"])
qc_df.to_csv(QC_DIR / "month_counts.csv", index=False)

summary = {
    "block": "1.2_corrected",
    "strategy": "temporal stratified sampling with month normalization",
    "base_per_month": BASE_PER_MONTH,
    "max_per_month": MAX_PER_MONTH,
    "seed": RANDOM_SEED,
    "total_tweets": int(qc_df["sampled"].sum()),
    "generated_at": datetime.utcnow().isoformat(),
    "output_root": str(OUTPUT_ROOT)
}

with open(QC_DIR / "summary.json", "w") as f:
    json.dump(summary, f, indent=2)

print("=" * 100)
print("✅ BLOCK 1.2 (CORRECTED) COMPLETED")
print(f"Total tweets in final corpus: {summary['total_tweets']:,}")
print(f"QC saved to: {QC_DIR}")
print("=" * 100)